# Generated by Django 5.2.7 on 2025-11-04 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='مفتاح الجلسة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='متصفح المستخدم')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='مسار الصفحة')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='الصفحة المرجعية')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الزيارة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='units_visit_user_id_4cec65_idx'), models.Index(fields=['-created_at'], name='units_visit_created_2c972b_idx')],
            },
        ),
    ]
