# Generated by Django 5.2.7 on 2025-11-08 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('purchases_maintenance', 'مشتريات وصيانة'), ('cleaning_supplies', 'مواد نظافة'), ('chlorine', 'كلور'), ('electricity', 'كهرباء'), ('plumbing', 'سباكة'), ('swimming_pools', 'مسابح'), ('cooling', 'تبريد'), ('landscaping', 'زراعة وتشجير'), ('mattress_upholstery', 'تنجيد مراتب'), ('blacksmithing', 'حدادة'), ('carpentry', 'نجارة'), ('aluminum', 'ألمنيوم'), ('shared', 'مشتركة'), ('other', 'أخرى')], max_length=50, null=True, verbose_name='فئة المصروف')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='expenses/invoices/', verbose_name='الفاتورة')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='units.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-created_at'],
            },
        ),
    ]
