# Generated by Django 5.2.7 on 2025-11-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الإثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='يوم الأسبوع')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر التأجير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='units.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'سعر الوحدة',
                'verbose_name_plural': 'أسعار الوحدات',
                'ordering': ['unit', 'day_of_week'],
                'unique_together': {('unit', 'day_of_week')},
            },
        ),
    ]
