# Generated by Django 5.2.7 on 2025-11-09 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_unitpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='units/gallery/', verbose_name='الصورة')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الصورة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='units.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'صورة وحدة',
                'verbose_name_plural': 'صور الوحدات',
                'ordering': ['-created_at'],
            },
        ),
    ]
