# Generated by Django 5.2.7 on 2025-11-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_unitimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitimage',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'صورة وحدة', 'verbose_name_plural': 'صور الوحدات'},
        ),
        migrations.AddField(
            model_name='unitimage',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='صورة مميزة'),
        ),
    ]
