# Generated by Django 5.2.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_alter_unitimage_options_unitimage_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('eid_al_fitr', 'عيد الفطر'), ('eid_al_adha', 'عيد الأضحى'), ('holiday', 'إجازة')], max_length=20, verbose_name='نوع السعر')),
                ('night_number', models.IntegerField(choices=[(1, 'الليلة الأولى'), (2, 'الليلة الثانية'), (3, 'الليلة الثالثة'), (4, 'الليلة الرابعة'), (5, 'الليلة الخامسة'), (6, 'الليلة السادسة')], verbose_name='رقم الليلة')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الليلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_pricing', to='units.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'سعر خاص',
                'verbose_name_plural': 'أسعار خاصة',
                'ordering': ['unit', 'pricing_type', 'night_number'],
                'unique_together': {('unit', 'pricing_type', 'night_number')},
            },
        ),
    ]

