# Generated by Django 5.2.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_specialpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(choices=[(20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=50, verbose_name='نسبة الأرباح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_percentage', to='units.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'نسبة الأرباح',
                'verbose_name_plural': 'نسب الأرباح',
                'ordering': ['unit'],
            },
        ),
    ]

