# Generated by Django 5.2.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0009_profitpercentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitpercentage',
            name='unit',
        ),
        migrations.AddField(
            model_name='profitpercentage',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_percentage', to=settings.AUTH_USER_MODEL, verbose_name='المالك (المستثمر)'),
        ),
        migrations.AlterField(
            model_name='profitpercentage',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_percentage', to=settings.AUTH_USER_MODEL, verbose_name='المالك (المستثمر)'),
        ),
    ]

