# Generated by Django 5.2.7 on 2025-11-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_alter_profitpercentage_unit_to_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profitpercentage',
            options={'ordering': ['owner'], 'verbose_name': 'نسبة الأرباح', 'verbose_name_plural': 'نسب الأرباح'},
        ),
    ]
