# Generated by Django 5.2.7 on 2025-11-22 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_alter_profitpercentage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(help_text='مثال: يوم التأسيس، اليوم الوطني، إلخ', max_length=200, verbose_name='اسم الإجازة')),
                ('holiday_date', models.DateField(verbose_name='تاريخ الإجازة')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الليلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='units.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'الإجازات',
                'ordering': ['holiday_date'],
                'unique_together': {('unit', 'holiday_date')},
            },
        ),
    ]
